name: SML/NJ Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Install deps (macOS)
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          # SML/NJ
          brew install --cask smlnj
          export PATH=/usr/local/smlnj/bin:"$PATH"
          echo "/usr/local/smlnj/bin" >> $GITHUB_PATH
          sml @SMLversion
          # dvipdfmx
          brew install --cask basictex
          eval "$(/usr/libexec/path_helper)"
          dvipdfmx --version
      - name: Gen DVI
        run: sml CI.sml
      - name: Gen PDF
        run: |
          dvipdfmx test1.dvi
          dvipdfmx test2.dvi
      - name: Upload DVI & PDF
        uses: actions/upload-artifact@v2
        with:
          name: dvi-pdf
          path: |
            *.dvi
            *.pdf
